### ISSUE TITLE
Sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld#5]
Creare un programma sfera.py che chieda all'utente
il raggio di una sfera (intero) e ne stampi superficie e volume

Note:
Per portare a termine il compito e'
necessaria la costante matematica pi greco.
Si puo' definire una variabile assegnandole tale valore:
```python
pi = 3.141592654
```
Oppure si puo' utilizzare quella gia'
definita nella libreria matematica:
```python
import math

...

math.pi

...
```

**Comment by FabioZTessitore** [comment]
fai attenzione a int e float

**Comment by CarloRuzzon** [comment]
Perchè, che problema c'è?

2016-11-02 11:17 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
prova ad inserire raggio 1 e vedi

**Comment by CarloRuzzon** [comment]
Come volume mi da il pigreco...

2016-11-02 11:21 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by CarloRuzzon** [comment]
risolto

2016-11-02 11:24 GMT+01:00 carlo ruzzon carloruzzon@gmail.com:

**Comment by FabioZTessitore** [comment]
ok, quindi ricorda di usare i float quando fai calcoli matematici
ps. perché invece l'area funziona?

**Comment by FabioZTessitore** [comment]
L'operatore modulo

Oltre alle classiche quattro operazioni
tutti i linguaggi di programmazione
mettono a disposizione una quinta operazione:
il modulo (o resto della divisione)

Apri l'interprete Python
$ python

e prova ad eseguire questi comandi

> > > 7 % 4
> > > [resto 3]
> > > 
> > > 10 % 2
> > > [resto 0]

**Comment by FabioZTessitore** [comment]
Espressioni booleane

Le espressioni booleane sono quelle espressioni
che restituiscono solo valore Vero (True) o Falso (False).

Si ottengono mediante l'uso degli operatori:

==    uguale
<     minore

> ```
> maggiore
> ```
> 
> <=    minore o uguale
> =    maggiore o uguale
> !=    diverso

Es. dopo aver lanciato l'interprete Python
prova ad eseguire questi comandi:

> > > 3 == 3
> > > [True]
> > > 
> > > 3 < 1
> > > [False]
> > > 
> > > 5 != 7
> > > [True]
> > > 
> > > 5 <= 7
> > > [True]

Operatori logici

Gli operatori logici (and, or, not) permettono di combinare espressioni booleane

> > > 3 <= 3 and 7 > 9
> > > [False, perche' solo la prima e' Vera]
> > > 
> > > 3 <= 3 or 7 > 9
> > > [True, perche' almeno la prima e' Vera]
> > > 
> > > not 10 < 7
> > > [True, perche' 10<7 e' False]

**Comment by CarloRuzzon** [comment]
Perchè python riesce a fare una moltiplicazione tra un intero e un decimale

2016-11-02 11:39 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
gli interi vengono automaticamente convertiti prima di fare un'operazione con un float.
Nel caso di prima invece c'era 4/3 (operazione tra soli interi)
