### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld#7]
Scrivi un programma che calcoli il volume di un cubo o di una sfera
in base ad una scelta effettuata dall'utente.
Se l'utente sceglie di calcolare il volume di un cubo,
il programma chiedera' l'input del relativo lato,
altrimenti chiedera' il raggio della sfera.

Esempio di esecuzione:
```bash
Calcolo del volume di un cubo o di una sfera
Effettua una scelta (1 - Cubo, 2 - Sfera)
? 1
Lato del cubo: 2
Il cubo di lato 2 ha volume 8
```

**Comment by FabioZTessitore** [comment]
la formula per il volume è errata

**Comment by CarloRuzzon** [comment]
aggiustato, ora carico anche l'altro

2016-11-02 20:47 GMT+01:00 Fabio Z Tessitore notifications@github.com:
