### ISSUE TITLE
PrimoGrado

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld#8]
Scrivi un programma che trovi la soluzione a equazioni di primo grado
nella forma ax+b=0, con a e b interi.

Il programma dovrebbe tener conto dei casi particolari: a, b o entrambi nulli.

**Comment by FabioZTessitore** [comment]
carica quello che hai fatto

**Comment by FabioZTessitore** [comment]
se hai un numero intero, ad esempio 3, e vuoi farlo diventare float puoi fare float(3)
allo stesso modo con le variabili

**Comment by CarloRuzzon** [comment]
Ci ho provato prof, ma comunque sia non risolve nulla, anzi complica le
cose e mi da come risultato 0, non riesco a capire

Il 3 nov 2016 12:02 PM, "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
guarda il file ...

ps. devi correggere i casi. Ti avevo scritto di considerare quando a, b, o **entrambi** sono nulli

**Comment by CarloRuzzon** [comment]
Appena arrivo a casa lo faccio

Il 3 nov 2016 12:10 PM, "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by CarloRuzzon** [comment]
fatto prof, provo a fare l'ultimo

2016-11-03 12:43 GMT+01:00 carlo ruzzon carloruzzon@gmail.com:

**Comment by CarloRuzzon** [comment]
Comunque grazie per il chiarimento sul float, perfettamente ricevuto

Il giorno 3 novembre 2016 15:00, carlo ruzzon carloruzzon@gmail.com ha
scritto:
