### ISSUE TITLE
SecGrado

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/helloworld#9]
Scrivi un programma che trovi le soluzioni a equazioni di secondo grado
nella forma ax^2+bx+c=0, con a, b e c interi.
Il programma dovrebbe tener conto dei casi particolari.

Per il calcolo della radice quadrata si puo' utilizzare la funzione `sqrt()`
della libreria matematica math
```python
import math

... math.sqrt() ...
```

**Comment by FabioZTessitore** [comment]
i casi sono fatti male, la soluzione è più semplice.
Prima di tutto considera i casi peggiori:
1) a, b, c tutti nulli
2) a, b nulli (quindi c non nullo)
3) a nullo (quindi b non nullo)
4) qui ci sono veramente le equazioni di 2^ grado e devi verificare il delta

**Comment by CarloRuzzon** [comment]
Lo rifaccio?

2016-11-03 16:26 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
lo devo rifare io?

**Comment by CarloRuzzon** [comment]
ahahahah vado

2016-11-03 16:31 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by CarloRuzzon** [comment]
Però comunque si trovava tutto

2016-11-03 16:31 GMT+01:00 carlo ruzzon carloruzzon@gmail.com:

**Comment by CarloRuzzon** [comment]
Prof io ho fatto, ma mettiamo caso che si inserisca un'equazione spuri o
pura, lui ce la darà come impossibile

2016-11-03 16:35 GMT+01:00 carlo ruzzon carloruzzon@gmail.com:

**Comment by FabioZTessitore** [comment]
aggiusta il terzo caso, non è necessario scrivere tutta quella roba, basta a==0

**Comment by CarloRuzzon** [comment]
Ma se proviamo a mettere 1 0 0 lui cercherà di calcolare il delta...

2016-11-03 16:49 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by CarloRuzzon** [comment]
Vabbe faccio come dite voi e basta

Il giorno 3 novembre 2016 16:53, carlo ruzzon carloruzzon@gmail.com ha
scritto:

**Comment by CarloRuzzon** [comment]
Fatto

Il giorno 3 novembre 2016 16:54, carlo ruzzon carloruzzon@gmail.com ha
scritto:

**Comment by FabioZTessitore** [comment]
se metti 1 0 0 sei proprio nel caso 3

**Comment by FabioZTessitore** [comment]
hai aggiustato l'if, ma devi aggiustare cosa calcolare

**Comment by CarloRuzzon** [comment]
Si ma in realtà l'equazione è nulla, io puntavo tutti i tipi di equazioni,
perciò avevo messo anche spurie e varie in quelo modo ci diceva tutto e
valeva per tutte le equazioni di 2° grado

2016-11-03 16:55 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
in realtà non sai la matematica

**Comment by CarloRuzzon** [comment]
Aahahhahah se lo dite voi, vabbene comunque ho aggiustato l'if e cambiato
il valore all'interno

2016-11-03 16:57 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma hai rimesso il vecchio codice ... aggiusta

**Comment by CarloRuzzon** [comment]
fatto...

2016-11-03 17:34 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
sei testardo
quando a è 0 devi calcolare la soluzione (unica)

**Comment by CarloRuzzon** [comment]
Va bene così?

2016-11-03 17:47 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ti sei avvicinato, ma ancora non va bene. Che fine ha fatto b?

**Comment by CarloRuzzon** [comment]
Me n'ero scordato, risolto

2016-11-03 20:08 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by CarloRuzzon** [comment]
Va bene?

Il 3 nov 2016 8:56 PM, "carlo ruzzon" carloruzzon@gmail.com ha scritto:
